let obj = {
	feeArr: [
        {   label:"公摊费",value:"PUBLIC_APPORTIONMENT_FEE",index:0,   },
        {   label:"空调流量费",value:"AIR_CONDITION_FEE",index:1,    },
        {   label:"服务费",value:"SERVICE_CHARGE",index:2, },
        {   label:"网络费",value:"NETWORK_FEE",index:3,},                                                   
        {   label:"有线电视费",value:"CATV",index:4,    },
        {   label:"水费",value:"WATER",index:5,  },         
        {   label:"电费",value:"POWER",index:6,  },
        {   label:"煤气费",value:"COAL",index:7,  },        
        {   label:"水卡押金",value:"WATER_CARD_DEPOSIT",index:9,   },                        
        {   label:"电卡押金",value:"ELECTRIC_CARD_DEPOSIT",index:10,    },
        {   label:"换房费",value:"EXCHANGE_HOUSES_FEE",index:11,   },
        {   label:"租金",value:"RENT",index:12,   },
        {   label:"保洁费",value:"CLEAN",index:13, },
        {   label:"电表赔偿费",value:"AMMETER_COMPENSATION",index:14,    },
        {   label:"押金",value:"PLEDGE",index:15, },
        {   label:"电费预存款",value:"POWER_PRE_DEPOSIT",index:16,   },
        {   label:"水费预存款",value:"WATER_PRE_DEPOSIT",index:17,   },
        {   label:"房东款",value:"TRANSFER_LANDLORD",index:18, },
        {   label:"家具费",value:"FURNITURE",index:19, },
        {   label:"公共能耗费",value:"PUBLIC_ENERGY_CONSUMPTION",index:20,   },
        {   label:"物业费",value:"PROPERTY",index:21,  },          
        {   label:"电梯费",value:"ELEVATOR",index:22,  },
        {   label:"煤气管道",value:"COAL",index:23,  },
        {   label:"物业管理费",value:"PROPERTY",index:24,  },
        {   label:"机顶盒",value:"STB",index:25,  },
        {   label:"网络机顶盒",value:"NET_STB",index:26,  },    
        {   label:"其它",value:"OTHER",index:8,  },
    ],
    reviewStatusArr:[
        {   label:"签订中",value:"IN_CONCLUSION",index:0, },
        {   label:"等待签字",value:"WAITING_SIGN",index:1, },
        {   label:"等待审核",value:"WAITING_AUDIT",index:2, },
        {   label:"审核拒绝",value:"REFUSE_TO_AUDIT",index:3, },
        {   label:"未履行",value:"NON_FULFILMENT",index:4, },
        {   label:"正常履行",value:"NORMAL_PERFORMANCE",index:5, },
        {   label:"到期",value:"EXPIRED",index:6, },
        {   label:"中途违约",value:"HALFWAY_BREACH",index:7, },        
        {   label:"审核中",value:"AUDITING",index:8, },
        {   label:"审核失败",value:"AUDIT_FAILED",index:9, },
        {   label:"等待确认",value:"WAITING_CONFIRM",index:10, },
        {   label:"完成",value:"FINISHED",index:11, },
        {   label:"等待分配",value:"INIT",index:12, },
        {   label:"等待接收",value:"ALLOCATED",index:13, },
        {   label:"进行中",value:"GOING",index:14, },
        {   label:"未修",value:"UNREPAIRED",index:15, },
        {   label:"等待初审",value:"FIRST_TRIAL",index:16, },
        {   label:"审核拒绝",value:"REFUSE_TO_AUDIT",index:17, },
        {   label:"发放成功",value:"SUCCESS",index:18, },
        {   label:"停止",value:"STOP",index:19, },
        {   label:"冻结",value:"FREEZING",index:20, },
        {   label:"等待支付",value:"WAITING_PAY",index:21, },
        {   label:"支付成功",value:"PAY_SUCCESS",index:22, },        
        {   label:"抵扣中",value:"DEDUCTIBLE",index:23, },        
        {   label:"等待检查",value:"WAITING_EXAMINE",index:24, },
        {   label:"房东违约",value:"LANDLORD_BREACH",index:25, },     
        {   label:"违约处理中",value:"BREACH_PROCESSING",index:26, },   
        {   label:"公司违约",value:"COMPANY_DEFAULT",index:27,    }, 
        {   label:"租客违约",value:"TENANT_BREACH",index:28,    },  
        {   label:"换房违约",value:"EXCHANGE_HOUSES_BREACH",index:29,    },  
        {   label:"房东变更",value:"LANDLORD_CHANGE",index:30,    }, 
        {   label:"转租违约",value:"SUBLET_BREACH",index:31,    },  
        {   label:"关闭",value:"CLOSE",index:32,    },  
    ],
    furnitureArr:[
        {   label:"空调",value:"1",index:0,    },
        {   label:"冰箱",value:"2",index:1,    },
        {   label:"电视机",value:"3",index:2,    },
        {   label:"洗衣机",value:"4",index:3,    },
        {   label:"煤气灶",value:"5",index:4,    },
        {   label:"热水器",value:"6",index:5,    },
        {   label:"微波炉",value:"7",index:6,    },
        {   label:"电磁炉",value:"8",index:7,    },
        {   label:"油烟机",value:"9",index:8,    },
        {   label:"床",value:"10",index:9,    },
        {   label:"床头柜",value:"11",index:10,    },
        {   label:"床垫",value:"12",index:11,    },
        {   label:"衣橱",value:"13",index:12,    },
        {   label:"沙发",value:"14",index:13,    },        
        {   label:"茶几",value:"15",index:14,    },
        {   label:"电视柜",value:"16",index:15,    },
        {   label:"电脑桌",value:"17",index:16,    },
        {   label:"餐桌",value:"18",index:17,    },
        {   label:"椅子",value:"19",index:18,    },
        {   label:"网络设备",value:"20",index:19,    },
        {   label:"窗帘",value:"21",index:20,    },
    ],    
    matchFurniture:{
        '1':[
            {   label:"挂式",value:"挂式"  },
            {   label:"柜式",value:"柜式"  },
            {   label:"嵌入式",value:"嵌入式"  },
            {   label:"中央",value:"中央"  },
        ],
        '2':[
            {   label:"单门",value:"单门"  },
            {   label:"双门",value:"双门"  },
            {   label:"多门",value:"多门"  },
        ],
        '3':[
            {   label:"台式",value:"台式"  },
            {   label:"液晶",value:"液晶"  },
        ],
        '4':[
            {   label:"滚筒式",value:"滚筒式"  },
            {   label:"直筒式",value:"直筒式"  },
            {   label:"迷你式",value:"迷你式"  },
        ],
        '5':[
            {   label:"台式",value:"台式"  },
            {   label:"嵌入式",value:"嵌入式"  },
        ],
        '6':[
            {   label:"天然气",value:"天然气"  },
            {   label:"太阳能",value:"太阳能"  },
            {   label:"电热",value:"电热"  },
            {   label:"空气能",value:"空气能"  },
        ],
        '7':[
             {   label:"普通",value:"普通"  },
             {   label:"豪华",value:"豪华"  },
        ],
        '8':[
             {   label:"普通",value:"普通"  },
             {   label:"豪华",value:"豪华"  },
        ],
        '9':[
             {   label:"普通",value:"普通"  },
             {   label:"豪华",value:"豪华"  },
        ],
        '10':[
             {   label:"普通",value:"普通"  },
             {   label:"豪华",value:"豪华"  },
        ],
        '11':[
             {   label:"普通",value:"普通"  },
             {   label:"豪华",value:"豪华"  },
        ],
        '12':[
             {   label:"棕绷",value:"棕绷"  },
             {   label:"模板",value:"模板"  },
             {   label:"软垫",value:"软垫"  },
             {   label:"席梦思",value:"席梦思"  },
        ],
        '13':[
             {   label:"普通",value:"普通"  },
             {   label:"豪华",value:"豪华"  },
             {   label:"固定",value:"固定"  },
             {   label:"活动",value:"活动"  },
        ],
        '14':[
             {   label:"布艺",value:"布艺"  },
             {   label:"藤制",value:"藤制"  },
             {   label:"皮质",value:"皮质"  },
             {   label:"木质",value:"木质"  },
        ],
        '15':[
             {   label:"藤制",value:"藤制"  },
             {   label:"玻璃",value:"玻璃"  },
             {   label:"木质",value:"木质"  },
        ],
        '16':[
             {   label:"固定",value:"固定"  },
             {   label:"活动",value:"活动"  },
        ],
        '17':[
             {   label:"普通",value:"普通"  },
             {   label:"豪华",value:"豪华"  },
        ],
        '18':[
             {   label:"藤制",value:"藤制"  },
             {   label:"玻璃",value:"玻璃"  },
             {   label:"木质",value:"木质"  },
        ],
        '19':[
             {   label:"藤制",value:"藤制"  },
             {   label:"塑料",value:"塑料"  },
             {   label:"木质",value:"木质"  },
             {   label:"铁艺",value:"铁艺"  },
        ],
        '20':[
             {   label:"猫",value:"猫"  },
             {   label:"路由器",value:"路由器"  },
             {   label:"电视机顶盒",value:"电视机顶盒"  },
             {   label:"网络机顶盒",value:"网络机顶盒"  },
        ],
        '21':[
             {   label:"无",value:"无"  },
        ],
    },
    supplierArr:[
        {   label:"杭州悦友楼宇设备工程有限公司",value:"13305713711"    },        
        {   label:"宁波家电风云电器",value:"13065804318"    },
        {   label:"杭州可米景观设计有限公司",value:"13777874123"    },
        {   label:"宁波家具轻纺城",value:"15958849009"    },
        {   label:"宜家",value:"4008002345"    },
        {   label:"网购",value:"无"    },
    ],
    identityTypeArr:[
          {   label:"身份（全部）",value:"",index:0,    },  
          {   label:"游客",value:"VISITOR",index:1,    },  
          {   label:"房东",value:"LANDLORD",index:2,    },  
          {   label:"租客",value:"TENANT",index:3,    },  
          {   label:"房东兼租客",value:"ALL",index:4,    },  
          {   label:"默认类型",value:"NORMAL",index:5,    },  
          {   label:"业务员",value:"SALESMAN",index:6,    },  
          {   label:"管理员",value:"ADMIN",index:7,    },  
          {   label:"财务员",value:"TREASURER",index:8,    },  
          {   label:"客服",value:"CUSTOMER_SERVICE",index:9,    },  
          {   label:"家政",value:"HOUSE_KEEPING",index:10,    },
    ],
    departmentArr:[
        {   label:"部门（全部）",value:"",index:0,    },  
        {   label:"宁波业务一部",value:"1",index:1,    },  
        {   label:"宁波业务二部",value:"2",index:2,    },  
        {   label:"宁波业务三部",value:"3",index:3,    },  
        {   label:"杭州业务一部",value:"4",index:4,    },  
        {   label:"杭州业务二部",value:"5",index:5,    },  
        {   label:"杭州业务三部",value:"6",index:6,    },  
        {   label:"苏州业务一部",value:"7",index:7,    },  
        {   label:"上海业务一部",value:"8",index:8,    },  
    ],
    defaultHandlerArr:[
        {   label:"吴玉丰",value:"115",index:0,    },  
        {   label:"韩江南",value:"6701",index:1,    },  
        {   label:"胡宇斌",value:"107",index:2,    },  
        {   label:"桑博豪",value:"24156",index:3,    },          
        {   label:"陈任鹏",value:"82",index:4,    },  
        {   label:"张明阳",value:"100",index:5,    },  
        {   label:"王佳男",value:"6700",index:6,    },  
        {   label:"韩军",value:"84",index:7,    },  
        {   label:"吴坤",value:"16918",index:8,    },          
        {   label:"杨恒",value:"6702",index:9,    },  
        {   label:"季暄朝",value:"23660",index:10,    },          
        {   label:"赵平",value:"26163",index:11,    },             
        {   label:"范伟平",value:"23320",index:12,    },  
        {   label:"张凯威",value:"16507",index:13,    },        
        {   label:"吴朋朋",value:"24913",index:14,    },  
        {   label:"严阿强",value:"26593",index:15,    },          
    ],
    repairerArr:[
        {   label:"王益洪",value:"11348",index:0,    },  
        {   label:"宣雪峰",value:"11351",index:1,    },  
    ],
    breachTypeArr:[
        {   label:"到期",value:"EXPIRED",index:0,    },  
        {   label:"公司违约",value:"COMPANY_DEFAULT",index:1,    },  
        {   label:"房东违约",value:"LANDLORD_BREACH",index:2,    },  
        {   label:"租客违约",value:"TENANT_BREACH",index:3,    },  
        {   label:"换房违约",value:"EXCHANGE_HOUSES_BREACH",index:4,    },  
        {   label:"转租违约",value:"SUBLET_BREACH",index:5,    },  
    ],
    repairOrderFurnitureArr:[
        {   label:"水电",value:"WATER_ELECTRICITY",index:0,    },  
        {   label:"电器",value:"APPLIANCE",index:1,    },          
        {   label:"安装",value:"INSTALLATION",index:2,    }, 
        {   label:"家具",value:"FURNITURE",index:3,    },  
        {   label:"门窗",value:"DOOR_WINDOW",index:4,    },  
        {   label:"墙体(纸)",value:"WALL",index:5,    }, 
        {   label:"疏通",value:"DREDGE",index:6,    },  
        {   label:"漏(渗)水",value:"LEAK",index:7,    },  
        {   label:"锁",value:"LOCK",index:8,    },  
        {   label:"窗帘",value:"CURTAIN",index:9,    },  
        {   label:"地板(线)",value:"FLOOR",index:10,    },  
        {   label:"空房检查",value:"EMPTY_ROOM_EXAMINATION",index:11,    },          
        {   label:"空房复查",value:"REEXAMINATION_OF_EMPTY_ROOM",index:12,    },  
        {   label:"其它",value:"OTHER",index:13,    },  
    ],
    repairOrderStatusArr:[
        {   label:"待分配",value:"INIT",index:0,    },  
        {   label:"待接收",value:"ALLOCATED",index:1,    },  
        {   label:"进行中",value:"GOING",index:2,    },  
        {   label:"完成",value:"FINISH",index:3,    },  
    ],
    houseStatusArr:[
        {   label:"收房签订中",value:"INIT",index:0,    },  
        {   label:"可出租",value:"SUCCESS",index:1,    },  
        {   label:"已发布",value:"PUBLISHED",index:2,    },  
        {   label:"已预定",value:"RESERVED",index:3,    },  
        {   label:"出租签订中",value:"LEASE_SIGNING",index:4,    },  
        {   label:"已出租",value:"RENTED",index:5,    },  
        {   label:"中途违约",value:"HALFWAY_BREACH",index:6,    },  
        {   label:"准备违约",value:"PREPARE_BREACH",index:7,    },  
        {   label:"到期",value:"EXPIRED",index:8,    },  
        {   label:"不可出租",value:"CANT_RENT",index:9,    },  
    ],
    agreementContractTypeArr:[
        {   label:"收房",value:"RECEIVE",index:0,    },  
        {   label:"收房续签",value:"RECEIVE_RENEW",index:1,    },  
        {   label:"房东变更",value:"LANDLORD_CHANGE",index:2,    },  
        {   label:"出租",value:"RENT",index:3,    },  
        {   label:"出租续签",value:"RENT_RENEW",index:4,    },  
        {   label:"换房",value:"EXCHANGE_HOUSES",index:5,    },  
        {   label:"转租",value:"SUBLET",index:6,    },  
    ],
    agreementChargeListArr:[
        {   label:"水",value:"WATER",index:0,    },  
        {   label:"电",value:"POWER",index:1,    },  
        {   label:"电梯费用",value:"ELEVATOR",index:2,    },  
        {   label:"煤气管道",value:"COAL",index:3,    },  
        {   label:"空调流量费",value:"AIR_CONDITION_FEE",index:4,    },  
        {   label:"服务费",value:"SERVICE_CHARGE",index:5,    },  
        {   label:"公摊费",value:"PUBLIC_APPORTIONMENT_FEE",index:6,    },  
        {   label:"网络费",value:"NETWORK_FEE",index:7,    },  
        {   label:"物业管理费",value:"PROPERTY",index:8,    },  
        {   label:"换房费",value:"EXCHANGE_HOUSES_FEE",index:9,    },  
        {   label:"转租费",value:"SUBLET_FEE",index:10    },  
    ],
    
    
};
export default {
    install: function(Vue) {
	   Object.defineProperty(Vue.prototype, 'StateData' , { value: obj });
	 }	
}